- name: installs nginx-extras
  apt:
    name: nginx-extras
    state: present

- name: configures nginx conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: configures nginx
  copy:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: copy rundeck acl script
  copy:
    src: files/acl_script.lua
    dest: /etc/rundecACL/RundeckACL.lua

- name: copy rundeck ACL json
  copy:
    src: files/acl.json
    dest: /etc/rundecACL/acl.json

- name: install luarocks
  apt:
    name: luarocks

- name: install json module
  command: luarocks install json-lua

- name: restarts nginx
  service:
    name: nginx
    state: restarted